spring:
  datasource:
    url: jdbc:mysql://mysql:3307/weekend
    username: user
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        hbm2ddl.auto: create-drop
        show_sql: true
        batch.size: 20
        current.session.context.class: org.springframework.orm.hibernate5.SpringSessionContext